name: Build and Publish Docker Images

on:
  workflow_dispatch:
    inputs:
      run-client-unit-tests:
        type: boolean
        description: Run the client unit tests
        required: false
        default: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Run client unit tests
        if: ${{ inputs.run-client-unit-tests }}
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/complex-demo-client-test -f ./client/Dockerfile.dev ./client
          docker run -e CI=true ${{ secrets.DOCKER_USERNAME }}/complex-demo-client-test npm test

      - name: Build Docker images
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/complex-demo-client ./client
          docker build -t ${{ secrets.DOCKER_USERNAME }}/complex-demo-nginx ./nginx
          docker build -t ${{ secrets.DOCKER_USERNAME }}/complex-demo-server ./server
          docker build -t ${{ secrets.DOCKER_USERNAME }}/complex-demo-worker ./worker

      - name: Publish Docker images
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/complex-demo-client
          docker push ${{ secrets.DOCKER_USERNAME }}/complex-demo-nginx
          docker push ${{ secrets.DOCKER_USERNAME }}/complex-demo-server
          docker push ${{ secrets.DOCKER_USERNAME }}/complex-demo-worker
